<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>    

<!DOCTYPE html>
<html>

	<head>
		<meta charset="ISO-8859-1">
		<title>add customer</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" />
	</head>

	<body>											<!-- mapping to validateForm in customer controller -->
			<div class="container">
				<div class="ui segment" style="margin-top: 20px">
					<form:form modelAttribute="customer" action="validateForm" class="ui form">
						
						<!-- need to add customerId to customer object -->
						<!-- it is null when we add customer because it is auto-generated by DB-->
						<!-- & available when we update customer -->
						<form:hidden path="id"/>
						
						<div class="field">
							First name(*)<form:input path="f_name" />
							<form:errors path="f_name"/>	<!-- for this add hibernate validation jar -->
						</div>
						
						<div class="field">					
							Last name(*)<form:input path="l_name"/>
							<form:errors path="l_name"/>
						</div>
						
						<div class="ui field">	
							email(*)<form:input path="email"/>
							<form:errors path="email"/>
						</div>
						
						<input class="ui button" type="submit" value="submit"> 
						
					</form:form>
				</div>
				<ul class="pager">
					<li class="previous">																		<!-- previous means left side  -->
					 	<a href="${pageContext.request.contextPath}/customer/list">Back to List</a>				<!-- bootstrap style  -->
					 </li>			
				</ul>
				
				
			</div>
	</body>
</html>